[project]
name = "valutatrade-hub"
version = "0.1.0"
description = "CLI for virtual currency portfolios and exchange-rate collection"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asciinema>=2.4.0",
    "prettytable>=3.18.0",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "ruff>=0.16.10",
]

[project.scripts]
valutatrade = "valutatrade_hub.cli.interface:main"

[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["valutatrade_hub"]
